sudo: required
dist: trusty
os: linux
language: generic
cache:
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/.ccache"
env:
  global:
    - MAKEJOBS=-j3
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
  matrix:
    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="" GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-gui"
    - HOST=x86_64-unknown-linux-gnu DEP_OPTS="" GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-gui "
    - HOST=x86_64-apple-darwin11 PACKAGES="gcc-multilib g++-multilib cmake libcap-dev libz-dev libbz2-dev" OSX_SDK=10.11 GOAL="deploy"
    - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc" GOAL="deploy" BITCOIN_CONFIG="--enable-gui" MAKEJOBS="-j2"
    - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc" GOAL="deploy" BITCOIN_CONFIG="--enable-gui" MAKEJOBS="-j2"
install:
    - if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
    - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
before_script:
    - unset CC; unset CXX
    - mkdir -p depends/SDKs depends/sdk-sources
    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then wget $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -O depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
    - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
script:
    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
    - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
    - BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
    - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
    - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
    - ./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
    - make distdir PACKAGE=bitcoin VERSION=$HOST
    - cd bitcoin-$HOST
    - ./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
    - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
    - mkdir -p $HOME/bin
    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
    - if [ -d $OUTDIR ]; then cp $OUTDIR/* $HOME/bin/ -rf; fi
    - if [ -n "$OSX_SDK" ]; then cp -rf Flashcoin-Qt.app $HOME/bin; fi
    - if [ -n "$OSX_SDK" ]; then cp -rf Flashcoin-Qt.dmg $HOME/bin; fi
    - if [ -f "flashcoin-0.10.3.0-win64-setup.exe" ]; then cp flashcoin-0.10.3.0-win64-setup.exe $HOME/bin; fi
    - if [ -f "flashcoin-0.10.3.0-win32-setup.exe" ]; then cp flashcoin-0.10.3.0-win32-setup.exe $HOME/bin; fi
    - ls -la $HOME/bin
    - ls -la $HOME/bin/*
after_script:
- echo $TRAVIS_COMMIT_RANGE
- echo $TRAVIS_COMMIT_LOG
notifications:
  irc: chat.freenode.net#multicoin-co
before_deploy: cd $HOME && tar -zcvf Flashcoin-$HOST.tar.gz $HOME/bin && ls -la $HOME
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: uZCv2ZQY4MhGtWnUnf5iDrFGo2r5OtvDtYrSEdO7vp8qdkhR2xh9vCk8f2Lxzolc91PkXwiQRry/DKFrFilG2hE3Duz/Cm8ECs7jvPB3cjTx+jQoKvkFUjqiTJ4es3qJP+kLtlzNuFFuW9DxRutog2XM9qGap39GJI1/0NKRvqgsDA0dCesbM46vYGRfmtERvkejIAXmwzRaO5zSBBZ15PZw8jtCf88VBY2gpprhkJGTCQTz61/6l60nHO6a8plFlvTitW3q5kOE+HHPhD7wj+CH/AjTsHIKRJgivEtlfhHecd8Fb88csx3U2BizqTHcCCSMdYiw+2I3WMGt8goOu8ZxZHnH4vtQ/Ec68xULXEdDD2igoJps2d8GZnWe1cQ1PtpGvo1gFeCkhVX6QHaazlHLtes4kNtwxauq2lByHPFqggBxHpCgDLVBZtLqF8DO1rBws9LPtUl86Oh8lF48eMIurV1vyqF6Hl4nZpWLmU9J5NUQdTYY5tQuSnA5xx30WEd/AJCPzhgvu/Xaj4NX2FQKG9KQpBRZ7ROk6RHOMDG/BkesnKCFiye4imZgWuYB3GCdW9IF2vtAiapjSFgJEmXCM2c9v2Qv2CBis27ucoXOFsQB9cYa9IZWMfUgU9eygJmWe/HvN4GQ2WSAra8nvPM3aTI0MBu5WiGnpsw+obs=
  file:
    - $HOME/Flashcoin-$HOST.tar.gz
  on:
    tags: true
    all_branches: true
